-- Rename only: tables and columns to snake_case (analytics tools expect it). No data changes.
ALTER TABLE "User" RENAME TO "users";
ALTER TABLE "Wallet" RENAME TO "wallets";
ALTER TABLE "Transaction" RENAME TO "wallet_transactions";
ALTER TABLE "Sport" RENAME TO "sports";
ALTER TABLE "Event" RENAME TO "events";
ALTER TABLE "Market" RENAME TO "markets";
ALTER TABLE "Outcome" RENAME TO "selections";
ALTER TABLE "Bet" RENAME TO "bets";
ALTER TABLE "BetSelection" RENAME TO "bet_legs";
ALTER TABLE "BookedSlip" RENAME TO "booked_slips";
ALTER TABLE "Pick" RENAME TO "picks";
ALTER TABLE "OtpCode" RENAME TO "otp_codes";
ALTER TABLE "AuditLog" RENAME TO "audit_logs";
ALTER TABLE "SuspendedMatch" RENAME TO "suspended_matches";
ALTER TABLE "users" RENAME COLUMN "emailVerifiedAt" TO "email_verified_at";
ALTER TABLE "users" RENAME COLUMN "bonusClaimedAt" TO "bonus_claimed_at";
ALTER TABLE "users" RENAME COLUMN "deletedAt" TO "deleted_at";
ALTER TABLE "users" RENAME COLUMN "phoneVerifiedAt" TO "phone_verified_at";
ALTER TABLE "users" RENAME COLUMN "firstName" TO "first_name";
ALTER TABLE "users" RENAME COLUMN "lastName" TO "last_name";
ALTER TABLE "users" RENAME COLUMN "referralCode" TO "referral_code";
ALTER TABLE "users" RENAME COLUMN "ageConfirmedAt" TO "age_confirmed_at";
ALTER TABLE "users" RENAME COLUMN "dateOfBirth" TO "date_of_birth";
ALTER TABLE "users" RENAME COLUMN "passwordHash" TO "password_hash";
ALTER TABLE "users" RENAME COLUMN "passwordChangedAt" TO "password_changed_at";
ALTER TABLE "users" RENAME COLUMN "displayName" TO "display_name";
ALTER TABLE "users" RENAME COLUMN "suspendedAt" TO "suspended_at";
ALTER TABLE "users" RENAME COLUMN "suspendedReason" TO "suspended_reason";
ALTER TABLE "users" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "wallets" RENAME COLUMN "userId" TO "user_id";
ALTER TABLE "wallet_transactions" RENAME COLUMN "walletId" TO "wallet_id";
ALTER TABLE "wallet_transactions" RENAME COLUMN "balanceAfter" TO "balance_after";
ALTER TABLE "wallet_transactions" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "events" RENAME COLUMN "sportId" TO "sport_id";
ALTER TABLE "events" RENAME COLUMN "homeTeam" TO "home_team";
ALTER TABLE "events" RENAME COLUMN "awayTeam" TO "away_team";
ALTER TABLE "events" RENAME COLUMN "startTime" TO "start_time";
ALTER TABLE "markets" RENAME COLUMN "eventId" TO "event_id";
ALTER TABLE "selections" RENAME COLUMN "marketId" TO "market_id";
ALTER TABLE "bets" RENAME COLUMN "userId" TO "user_id";
ALTER TABLE "bets" RENAME COLUMN "totalOdds" TO "total_odds";
ALTER TABLE "bets" RENAME COLUMN "potentialPayout" TO "potential_payout";
ALTER TABLE "bets" RENAME COLUMN "idempotencyKey" TO "idempotency_key";
ALTER TABLE "bets" RENAME COLUMN "createdAt" TO "placed_at";
ALTER TABLE "bets" RENAME COLUMN "settledAt" TO "settled_at";
ALTER TABLE "bet_legs" RENAME COLUMN "betId" TO "bet_id";
ALTER TABLE "bet_legs" RENAME COLUMN "outcomeId" TO "selection_id";
ALTER TABLE "bet_legs" RENAME COLUMN "matchId" TO "match_id";
ALTER TABLE "bet_legs" RENAME COLUMN "marketLabel" TO "market_label";
ALTER TABLE "bet_legs" RENAME COLUMN "oddsAtPlacement" TO "odds";
ALTER TABLE "booked_slips" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "picks" RENAME COLUMN "deviceId" TO "device_id";
ALTER TABLE "picks" RENAME COLUMN "matchId" TO "match_id";
ALTER TABLE "picks" RENAME COLUMN "homeLogo" TO "home_logo";
ALTER TABLE "picks" RENAME COLUMN "awayLogo" TO "away_logo";
ALTER TABLE "picks" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "picks" RENAME COLUMN "updatedAt" TO "updated_at";
ALTER TABLE "otp_codes" RENAME COLUMN "codeHash" TO "code_hash";
ALTER TABLE "otp_codes" RENAME COLUMN "expiresAt" TO "expires_at";
ALTER TABLE "otp_codes" RENAME COLUMN "consumedAt" TO "consumed_at";
ALTER TABLE "otp_codes" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "audit_logs" RENAME COLUMN "adminId" TO "admin_id";
ALTER TABLE "audit_logs" RENAME COLUMN "targetType" TO "target_type";
ALTER TABLE "audit_logs" RENAME COLUMN "targetId" TO "target_id";
ALTER TABLE "audit_logs" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "suspended_matches" RENAME COLUMN "matchId" TO "match_id";
ALTER TABLE "suspended_matches" RENAME COLUMN "createdBy" TO "created_by";
ALTER TABLE "suspended_matches" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "users" RENAME CONSTRAINT "User_pkey" TO "users_pkey";
ALTER TABLE "wallets" RENAME CONSTRAINT "Wallet_pkey" TO "wallets_pkey";
ALTER TABLE "wallet_transactions" RENAME CONSTRAINT "Transaction_pkey" TO "wallet_transactions_pkey";
ALTER TABLE "sports" RENAME CONSTRAINT "Sport_pkey" TO "sports_pkey";
ALTER TABLE "events" RENAME CONSTRAINT "Event_pkey" TO "events_pkey";
ALTER TABLE "markets" RENAME CONSTRAINT "Market_pkey" TO "markets_pkey";
ALTER TABLE "selections" RENAME CONSTRAINT "Outcome_pkey" TO "selections_pkey";
ALTER TABLE "bets" RENAME CONSTRAINT "Bet_pkey" TO "bets_pkey";
ALTER TABLE "bet_legs" RENAME CONSTRAINT "BetSelection_pkey" TO "bet_legs_pkey";
ALTER TABLE "booked_slips" RENAME CONSTRAINT "BookedSlip_pkey" TO "booked_slips_pkey";
ALTER TABLE "picks" RENAME CONSTRAINT "Pick_pkey" TO "picks_pkey";
ALTER TABLE "otp_codes" RENAME CONSTRAINT "OtpCode_pkey" TO "otp_codes_pkey";
ALTER TABLE "audit_logs" RENAME CONSTRAINT "AuditLog_pkey" TO "audit_logs_pkey";
ALTER TABLE "suspended_matches" RENAME CONSTRAINT "SuspendedMatch_pkey" TO "suspended_matches_pkey";
ALTER TABLE "wallets" RENAME CONSTRAINT "Wallet_userId_fkey" TO "wallets_user_id_fkey";
ALTER TABLE "wallet_transactions" RENAME CONSTRAINT "Transaction_walletId_fkey" TO "wallet_transactions_wallet_id_fkey";
ALTER TABLE "events" RENAME CONSTRAINT "Event_sportId_fkey" TO "events_sport_id_fkey";
ALTER TABLE "markets" RENAME CONSTRAINT "Market_eventId_fkey" TO "markets_event_id_fkey";
ALTER TABLE "selections" RENAME CONSTRAINT "Outcome_marketId_fkey" TO "selections_market_id_fkey";
ALTER TABLE "bets" RENAME CONSTRAINT "Bet_userId_fkey" TO "bets_user_id_fkey";
ALTER TABLE "bet_legs" RENAME CONSTRAINT "BetSelection_betId_fkey" TO "bet_legs_bet_id_fkey";
ALTER TABLE "bet_legs" RENAME CONSTRAINT "BetSelection_outcomeId_fkey" TO "bet_legs_selection_id_fkey";
ALTER INDEX "User_email_key" RENAME TO "users_email_key";
ALTER INDEX "User_phone_key" RENAME TO "users_phone_key";
ALTER INDEX "Wallet_userId_key" RENAME TO "wallets_user_id_key";
ALTER INDEX "Transaction_walletId_createdAt_idx" RENAME TO "wallet_transactions_wallet_id_created_at_idx";
ALTER INDEX "Sport_slug_key" RENAME TO "sports_slug_key";
ALTER INDEX "Bet_ticket_key" RENAME TO "bets_ticket_key";
ALTER INDEX "Bet_userId_createdAt_idx" RENAME TO "bets_user_id_placed_at_idx";
ALTER INDEX "Bet_userId_idempotencyKey_key" RENAME TO "bets_user_id_idempotency_key_key";
ALTER INDEX "BetSelection_matchId_idx" RENAME TO "bet_legs_match_id_idx";
ALTER INDEX "BetSelection_result_kickoff_idx" RENAME TO "bet_legs_result_kickoff_idx";
ALTER INDEX "Pick_day_idx" RENAME TO "picks_day_idx";
ALTER INDEX "Pick_day_deviceId_matchId_key" RENAME TO "picks_day_device_id_match_id_key";
ALTER INDEX "OtpCode_phone_purpose_createdAt_idx" RENAME TO "otp_codes_phone_purpose_created_at_idx";
ALTER INDEX "AuditLog_createdAt_idx" RENAME TO "audit_logs_created_at_idx";
ALTER INDEX "AuditLog_targetType_targetId_idx" RENAME TO "audit_logs_target_type_target_id_idx";
