// Build step for the promo slides and game tiles (run before dev and build, on both sites):
//  1. a WebP copy next to each .jpg (about half the size; browsers without WebP keep the .jpg),
//  2. a short version stamp from each file's contents, so image URLs change when the image does
//     (browsers can then keep images for a year and still get a new one right away).
// Replacing an image is just: swap the .jpg and push. Usage: node optimize-images.mjs <public dir>
import { createHash } from "node:crypto";
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";

const publicDir = path.resolve(process.argv[2] ?? "public");
const FOLDERS = ["slides", "games"];
const out = fileURLToPath(new URL("../src/redesign/imageVersions.gen.ts", import.meta.url));

// sharp is resolved from the project being built (frontend or web), whichever has it installed.
let sharp = null;
try { sharp = createRequire(path.join(process.cwd(), "noop.js"))("sharp"); } catch { console.warn("optimize-images: sharp not installed, skipping WebP (JPGs still work)"); }

const versions = {};
for (const folder of FOLDERS) {
  const dir = path.join(publicDir, folder);
  if (!existsSync(dir)) continue;
  for (const name of readdirSync(dir).filter((n) => /\.jpe?g$/i.test(n)).sort()) {
    const src = path.join(dir, name);
    const bytes = readFileSync(src);
    const v = createHash("sha1").update(bytes).digest("hex").slice(0, 8);
    const webp = src.replace(/\.jpe?g$/i, ".webp");
    let hasWebp = existsSync(webp) && statSync(webp).mtimeMs >= statSync(src).mtimeMs;
    if (!hasWebp && sharp) {
      try { await sharp(bytes).webp({ quality: 80, effort: 6 }).toFile(webp); hasWebp = true; }
      catch (err) { console.warn(`optimize-images: ${name}: ${err.message}`); }
    }
    versions[`/${folder}/${name}`] = { v, webp: hasWebp };
  }
}

const body = `// Generated by frontend/scripts/optimize-images.mjs before each dev/build. Do not edit.
export const IMAGE_VERSIONS: Record<string, { v: string; webp: boolean }> = ${JSON.stringify(versions, null, 2)};
`;
if (!existsSync(out) || readFileSync(out, "utf8") !== body) writeFileSync(out, body);
console.log(`optimize-images: ${Object.keys(versions).length} images (${Object.values(versions).filter((x) => x.webp).length} with WebP)`);
